---
version: 0.2
phases:
  build:
    commands:
      - aws cloudformation package --template-file sam.yaml
                                   --s3-bucket mxco86-deployment
                                   --output-template-file sam-pkg.yaml
artifacts:
  type: zip
  files:
    - sam.yaml
    - sam-pkg.yaml
